# SITE CONFIGURATION
title: Boone Woodworks
author: dboone
description: # Meta description of Homepage
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://dboone.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}

tagline:
hero_img: suspended-oak-leaf
email: your-email@domain.com # email for form submission
github_username: dboone
service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

sass:
  sass_dir: _sass 
 
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
